export const dataStore = [
    {},
    { value: null },
    { a: 1, b: "2asd", c: Date(), d: true },
    { value: { inner: null } },
    { value: { inner: { inner1: null } } },
    { value: 1 },
    { value: { inner: 1 } },
    { value: "test" },
    { value: "2003-01-05T21:32:44.945Z" },
    { strValue: "test", emptyValue: {} },
    { strValue: "test", notEmptyValue: { test: "test" } },
    {
        test: {
            nullValue: null,
            notEmptyValue: { test: "" },
            intValue: -1,
            strValue: "test",
            dateValue: "2003-01-05T21:32:44.945Z",
            boolValue: true
        }
    },
    {
        nested1: {
            nested2: {
                nested3: {
                    nested4: {
                        nested5: {
                            number: 11,
                            nested6: { nested7: { intValue: -1 } }
                        }
                    }
                }
            }
        }
    },
    { arr: [] },
    { arr: ["test1", "test2", "test3"] },
    { a: [["array-item-1"], ["array-item-1", "array-item-2"]] },
    { arr: [null, null, null] },
    { arr: [[null], [[]], [[1, 2, 3]]] },
    { arr: [{ strValue: "test" }, {}, { intValue: 1, dateValue: new Date() }, { value: null }] },
    { arr: [[1, 2, 3], [1, "2", 3], [], [true, false], [[1, 2], [3, 4]]] },
    { arr: [-1, 10.22, 10.111111111111, "test", true, false, "2003-01-05T21:32:44.945Z", null, {}, { test: null }, { test: "test" }, [], [[]], [{}, []]] },
    {
        snapshot: [{ symbol: "AAPL", price: 119.948, sequence: 535 }, {
            symbol: "MSFT",
            price: 45.745,
            sequence: 536
        }, { symbol: "GOOG", price: 68.98, sequence: 537 }, {
            symbol: "FB",
            price: 537.362,
            sequence: 538
        }, { symbol: "YHOO", price: 49.387, sequence: 539 }], lastUpdateSeq: 540
    },
    {
        test: [{
            id: "3bc6d7a5-81e0-403c-bb14-002f582fbb42",
            sequenceId: null,
            type: "Execution",
            source: "OMS",
            sourceNotificationId: "OMS_cihqc7sxh0000s8ipuu4ozc6t",
            title: "Darketofzocmetruvtufultumhubenagaf.",
            notificationTime: "2041-09-05T01:13:14.820Z",
            creationTime: "2015-12-03T14:28:13.496Z",
            severity: "Info",
            description: "Mofmihnicawbuzsauvacihvomutvatvungukib.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            attributes: [{ key: "ne", value: { stringValue: "vugahu" } }, {
                key: "mumtuvfih",
                value: { stringValue: "hojigi" }
            }],
            target: { groups: ["Ontario"] },
            reminder: { remindPeriod: 120 }
        }, {
            id: "054ce16b-d759-4016-91f4-6e5fa6dd5a1b",
            sequenceId: null,
            type: "Alert",
            source: "GNS",
            sourceNotificationId: "GNS_cihqbupsc00009cipgq2txnro",
            title: "Belzolicbukgagadativzi.",
            notificationTime: "2027-08-20T05:41:56.728Z",
            creationTime: "2015-12-03T14:18:02.894Z",
            severity: "Warn",
            description: "Vucjabimberfehegatuperbeurtiveliucidoz.",
            state: "Closed",
            isRead: false,
            revision: 0,
            attributes: [{ key: "te", value: { stringValue: "buga" } }, {
                key: "vume",
                value: { stringValue: "elmi" }
            }],
            lifetime: { expiresAt: "2071-01-20T07:13:32.835Z" },
            target: { users: ["HowardGriffin", "FannieMassey"] }
        }, {
            id: "002e26bb-96fa-4cfc-b841-649693e7583c",
            sequenceId: null,
            type: "Workflow",
            source: "UNIXTimestamp",
            sourceNotificationId: "BPMEngine_cihpzicf800006wip5iei10lq",
            title: "Gisizjolawzobzasnufu.",
            notificationTime: "2084-11-10T03:09:15.631Z",
            creationTime: "2015-02-07T14:10:38.2275004+02:00",
            severity: "Warn",
            description: "Kupgezvedgepobjapadazusabakefenudofdamitkobajsajbertateeljo.",
            state: "Active",
            isRead: false,
            revision: 0,
            lifetime: { expiresIn: 53990 }
        }, {
            id: "2e9d9954-8fb9-4e67-91e4-2a9ae59d6ad6",
            sequenceId: null,
            type: "Execution",
            source: "OMS",
            sourceNotificationId: "OMS_cihqcrrr000011cipa4a853ld",
            title: "Gitvabkeezjemipevfekkekwumoibrilochumahoav.",
            notificationTime: "2050-10-15T08:06:41.346Z",
            creationTime: "2015-12-03T14:43:45.084Z",
            severity: "Warn",
            description: "Zoidekzagpujhuhupfuwtusecvobumunetargejafonnocbobetiklorzu.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            attributes: [{ key: "woisiad", value: { stringValue: "boshar" } }],
            target: { users: ["RichardChristensen"], groups: ["Manitoba"] }
        }, {
            id: "2d8befc7-237e-417e-9dba-6fa1cc3b5cda",
            sequenceId: null,
            type: "Workflow",
            source: "BPMEngine",
            sourceNotificationId: "BPMEngine_cihqcnowm00001cip5m7tamvh",
            title: "Sabbezagtibvisebiogevukpuazfebumni.",
            notificationTime: "2034-12-26T02:14:13.919Z",
            creationTime: "2015-12-03T14:40:34.777Z",
            severity: "Info",
            description: "Cabibriisemomifodovpowduzakadmeddajsunijsedtuwepiofkuijvu.",
            state: "Active",
            isRead: false,
            revision: 0,
            attributes: [{ key: "vedda", value: { stringValue: "nu" } }],
            target: { users: ["HuldaPowers", "LeonManning"] },
            reminder: { remindPeriod: 180 }
        }, {
            id: "8c590cd7-7fc5-41eb-9aa3-37e7922979a4",
            sequenceId: null,
            type: "Alert",
            source: "Eikon",
            sourceNotificationId: "Eikon_cihqcfma0000074ip0849z2p7",
            title: "Paapezumtenotuhmeshoglenematuhdeihotogkezangapnicre.",
            notificationTime: "2093-02-14T23:58:29.829Z",
            creationTime: "2015-12-03T14:34:18.122Z",
            severity: "Error",
            description: "Todiagijodiitoehuahivezotogbebmedid.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            attributes: [{ key: "rebbe", value: { stringValue: "hewjasit" } }],
            target: { groups: ["Nunavut"] }
        }, {
            id: "463b7116-5a02-478d-9ab8-4e593d3e6fda",
            sequenceId: null,
            type: "Notice",
            source: "Operate",
            sourceNotificationId: "Operate_cihqc840y0002s8ipb07d6lcv",
            title: "Wiewdeljipruvatisgukegeef.",
            notificationTime: "2031-06-21T04:51:40.645Z",
            creationTime: "2015-12-03T14:28:27.874Z",
            severity: "Warn",
            description: "Pareipowezojafkezhombadilezfedmegoacozustadigesuphegobaj.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            attributes: [{ key: "pekmig", value: { stringValue: "segnifze" } }],
            lifetime: { expiresIn: 45437 },
            target: { users: ["MaggieStokes", "LuluPorter"], groups: ["NewBrunswick"] },
            reminder: { remindPeriod: 270 }
        }, {
            id: "f3ec5833-8420-442c-8e1b-3849d65965d2",
            sequenceId: null,
            type: "Alert",
            source: "Outlook",
            sourceNotificationId: "Outlook_cihp2li2l0001gsip3lapxmv0",
            title: "Onuzagoutdeutasewitarumojiro.",
            notificationTime: "2015-11-08T01:46:14.191Z",
            creationTime: "2015-12-02T17:11:10.270Z",
            severity: "Info",
            description: "Togkekupofutrobigampugahbusbeokiarijefitadgukref.",
            state: "Active",
            isRead: false,
            revision: 0,
            attributes: [{ key: "wukukvew", value: { stringValue: "hulvewdu" } }, {
                key: "mahogag",
                value: { stringValue: "ni" }
            }],
            target: { users: ["JacksonOwens", "EmilyLeonard"], groups: ["Manitoba"] }
        }, {
            id: "87ed5b2a-c989-4643-ae19-dbb0d89b97f2",
            sequenceId: null,
            type: "Activity",
            source: "GNS",
            sourceNotificationId: "GNS_cihp1umr80000gsippt5ml1du",
            title: "Jatecucocejatogeguaplizikufuppivgehipcawaotfifipja.",
            notificationTime: "2080-04-06T07:51:21.419Z",
            creationTime: "2015-12-02T16:50:16.633Z",
            severity: "Info",
            description: "Utienpiirasahhotajegvijhaidasivugivoljaotodauvewajejeididitudemifoz.",
            state: "Active",
            isRead: false,
            revision: 0,
            attributes: [{ key: "siriz", value: { stringValue: "na" } }, {
                key: "ca",
                value: { stringValue: "inpimod" }
            }],
            target: { groups: ["PrinceEdwardIsland"] }
        }, {
            id: "1a1bd623-082f-4ef2-92d9-9fe4697715f9",
            sequenceId: null,
            type: "Workflow",
            source: "BPMEngine",
            sourceNotificationId: "BPMEngine_cihqc81w30001s8ip0juf7ivf",
            title: "Uhiumbiazitimuceknoigweebza.",
            notificationTime: "2015-03-31T07:03:44.403Z",
            creationTime: "2015-12-03T14:28:25.107Z",
            severity: "Info",
            description: "Gimonaracihertapeffabtiffajzisarocoperotket.",
            state: "Closed",
            isRead: false,
            revision: 0,
            lifetime: { expiresIn: 43594 },
            target: { groups: ["NewfoundlandandLabrador"] }
        }, {
            id: "740dbc0a-7d2b-440a-9c2d-cc6fc4a7abd4",
            sequenceId: null,
            type: "Alert",
            source: "Eikon",
            sourceNotificationId: "Eikon_cihqcvv4i0000ckip9bamtif6",
            title: "Naknuwetefocuhcadgaropobekohpalu.",
            notificationTime: "2038-05-08T04:43:19.003Z",
            creationTime: "2015-12-03T14:46:56.084Z",
            severity: "Error",
            description: "Mogwipofweepolupevwugujkahwiedfokiwremkueholaeslikojrivgoocoluezu.",
            state: "Closed",
            isRead: false,
            revision: 0,
            attributes: [{ key: "gi", value: { stringValue: "desaf" } }, {
                key: "fer",
                value: { stringValue: "anoze" }
            }],
            target: { users: ["AlvinPope", "WinnieFowler"] }
        }, {
            id: "150c755e-af1b-46c2-98d1-3051f5860e38",
            sequenceId: null,
            type: "Workflow",
            source: "BPMEngine",
            sourceNotificationId: "BPMEngine_cihqfisgg0000q8ip01sitjm3",
            title: "Anipagihkocinonfuravcalucisisremkodamsucrovpeoz.",
            notificationTime: "2073-01-15T23:43:11.245Z",
            creationTime: "2015-12-03T16:00:44.945Z",
            severity: "Warn",
            description: "Bopluurjeebipuspogewvuolikoberfuwohiifacvamove.",
            state: "Closed",
            isRead: false,
            revision: 0,
            lifetime: { expiresIn: 61074 },
            target: { users: ["DellaBecker", "JeffreyCain", "FrancisBryan"], groups: ["Yukon"] }
        }, {
            creationTime: "2014-07-08T09:02:21.377",
            description: "Order12345tobuy100sharesofVOD.Lat0.9filledwith50lots",
            id: "fead152f382443bd9907e966670c9d3a",
            lifetime: { expiresAt: "2014-07-08T09:02:21.377" },
            notificationTime: "2014-07-08T09:02:21.377",
            revision: 1,
            sequenceId: 1,
            severity: "Info",
            source: "OMS",
            sourceNotificationId: "101",
            state: "Closed",
            tags: [{ key: "type", value: "execution" }, { key: "orderStatus", value: "filled" }],
            target: { groups: ["SalesTrader", "ProgramTrader"] },
            title: "Bought50VOD.L@0.9",
            type: "TRADING"
        }, {
            creationTime: "2015-07-08T09:02:21.377",
            description: "Order12346tosell100sharesofVOD.Lat1.2filledwith30lots",
            id: "f62abdf6500b4fba9387252fd60b8875",
            lifetime: { expiresAt: "2015-07-08T09:02:21.377" },
            notificationTime: "2015-07-08T09:02:21.377",
            revision: 1,
            sequenceId: 2,
            severity: "Info",
            source: "OMS",
            sourceNotificationId: "102",
            state: "Active",
            tags: [{ key: "type", value: "execution" }, { key: "orderStatus", value: "partiallyFilled" }],
            target: { _users: ["N559541", "N630647"] },
            title: "Sold30VOD.L@1.2",
            type: "TRADING"
        }, {
            creationTime: "2015-07-08T09:02:21.377",
            description: "Duetomaintenance,yourmachinewillbeautomaticallyrebootedin30minutes.Pleasesaveyourwork.",
            id: "b801f81d701f4fdf95f206413ef4e1c0",
            lifetime: { expiresAt: "2015-07-08T09:02:21.377" },
            notificationTime: "2015-07-08T09:02:21.377",
            revision: 1,
            sequenceId: 3,
            severity: "Warn",
            source: "OPERATE",
            sourceNotificationId: "1795",
            state: "Closed",
            tags: [{ key: "importance", value: "high" }, { key: "type", value: "reboot" }],
            target: { group: ["Users"] },
            title: "Yourmachinewillberebootedin30minutes",
            type: "NOTIFICATION"
        }, {
            creationTime: "2015-07-08T09:02:21.377",
            description: "Duetomaintenance,yourmachinewillbeautomaticallyrebootedin45minutes.Pleasesaveyourwork.",
            id: "000cecad49cf4edb8d24858fa1f81a4e",
            lifetime: { expiresAt: "2015-07-08T09:02:21.377" },
            notificationTime: "2015-07-08T09:02:21.377",
            revision: 1,
            sequenceId: 4,
            severity: "Warn",
            source: "OPERATE",
            sourceNotificationId: "1796",
            state: "Active",
            tags: [{ key: "importance", value: "high" }, { key: "type", value: "reboot" }],
            target: { group: ["Users"] },
            title: "Yourmachinewillberebootedin45minutes",
            type: "NOTIFICATION"
        }, {
            id: "3de53c5b-7ae0-432b-b534-3ab841c8bd23",
            sequenceId: null,
            type: "Alert",
            source: "Eikon",
            sourceNotificationId: "Eikon_cijbgcmi50000roh3giimjo6b",
            title: "Pomiucuwojukezatanirahotdahwedu.",
            notificationTime: "2050-04-18T22:47:53.418Z",
            creationTime: "2016-01-12T13:46:48.944Z",
            severity: "Error",
            description: "Fonolebosonlaefacuizosubcowtiblanutvefjoppuklovotza.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            attributes: [{ key: "tuwjipen", value: { stringValue: "pigliema" } }],
            lifetime: { expiresIn: 74153 },
            target: { users: ["ChaseMcKenzie"] },
            reminder: { remindPeriod: 270 }
        }, {
            id: "cda702da-8563-4520-b015-ad093bd5f967",
            sequenceId: null,
            type: "Alert",
            source: "GNS",
            sourceNotificationId: "GNS_cijbgco800001roh33ei54sv1",
            title: "Udbirhipidoudpermuigoduwkek.",
            notificationTime: "2065-07-09T08:18:29.401Z",
            creationTime: "2016-01-12T13:46:51.170Z",
            severity: "Info",
            description: "Ajurofsovrurohiwodecaneefumabputkoegzewdasoip.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            attributes: [{ key: "jeti", value: { stringValue: "tigaag" } }],
            target: { users: ["MaudMcBride", "AdelineHoffman", "CameronStanley"], groups: ["Quebec"] },
            reminder: { remindPeriod: 30 }
        }, {
            id: "ebe6f016-99fb-44c4-9f11-4e398223fd98",
            sequenceId: null,
            type: "Alert",
            source: "Outlook",
            sourceNotificationId: "Outlook_cijbgcpkh0002roh3dyjfju4f",
            title: "Demuabunugsijbokbesuhejofulcujzediusakekumtour.",
            notificationTime: "2065-05-09T06:30:15.610Z",
            creationTime: "2016-01-12T13:46:52.914Z",
            severity: "Warn",
            description: "Anoreecatozkogunaagomumamubunomipecwausiunki.",
            state: "Closed",
            isRead: false,
            revision: 0,
            attributes: [{ key: "utbab", value: { stringValue: "de" } }, {
                key: "wogke",
                value: { stringValue: "orageb" }
            }],
            lifetime: { expiresAt: "2040-03-15T10:35:18.421Z" },
            target: { users: ["JoelSanders"] },
            reminder: { remindPeriod: 90 }
        }, {
            id: "303fb806-591c-4def-9c68-f08a41f59c10",
            sequenceId: null,
            type: "Alert",
            source: "Eikon",
            sourceNotificationId: "Eikon_cijbgcqar0003roh3lp84p4kt",
            title: "Pubtuwurezjeugoemdecmufatpe.",
            notificationTime: "2016-02-25T08:28:22.299Z",
            creationTime: "2016-01-12T13:46:53.859Z",
            severity: "Info",
            description: "Nasobapgipwojatoksonucorudovcubmuccurekcelijvuencatmum.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            attributes: [{ key: "sebiz", value: { stringValue: "mujuh" } }, {
                key: "pazovi",
                value: { stringValue: "iv" }
            }],
            lifetime: { expiresIn: 30898 },
            target: { users: ["JeromeMarsh", "OllieBurgess"] }
        }, {
            id: "c835f479-a82e-4456-be44-0a1c18b79d14",
            sequenceId: null,
            type: "Execution",
            source: "OMS",
            sourceNotificationId: "OMS_cijbgcr3h0004roh3nl1i4dlu",
            title: "Vezcuburiheatocacazunijig.",
            notificationTime: "2027-06-05T06:05:38.859Z",
            creationTime: "2016-01-12T13:46:54.895Z",
            severity: "Warn",
            description: "Pusjozvipegrufabbakcostujiwozadoveclubfekputnadbam.",
            state: "Closed",
            isRead: false,
            revision: 0,
            target: { users: ["MaudLuna"], groups: ["Yukon"] },
            reminder: { remindPeriod: 300 }
        }, {
            id: "2603f6d5-efad-462e-936d-571fe3b2caea",
            sequenceId: null,
            type: "Alert",
            source: "Eikon",
            sourceNotificationId: "Eikon_cijbgcwaq0005roh3xyfzwwmt",
            title: "Ilnihasikdoinapudrorwecezmavaocpe.",
            notificationTime: "2036-03-29T05:42:38.037Z",
            creationTime: "2016-01-12T13:47:01.634Z",
            severity: "Warn",
            description: "Ovopulbekseslowcufrigogdivhezceubojugbibbudocuvihilzut.",
            state: "Active",
            isRead: false,
            revision: 0,
            lifetime: { expiresIn: 44990 },
            target: { users: ["LukeAnderson", "MaxPerez", "IreneBowers"] },
            reminder: { remindPeriod: 60 }
        }, {
            id: "ea3ee62a-0ba2-428e-a026-a5412bd476ea",
            sequenceId: null,
            type: "Workflow",
            source: "BPMEngine",
            sourceNotificationId: "BPMEngine_cijbgd0l10006roh3k039v94l",
            title: "Hazcakjefiwacomtaabunulumfugkibwutgagibaahardipeb.",
            notificationTime: "2065-05-06T07:14:33.311Z",
            creationTime: "2016-01-12T13:47:07.190Z",
            severity: "Info",
            description: "Nergaavoufofobegcaehjiwecanbuwomajzolmizfiwugefukujothelzorut.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            attributes: [{ key: "leje", value: { stringValue: "rimuda" } }],
            lifetime: { expiresAt: "2063-05-30T06:53:18.394Z" },
            target: { users: ["RogerMurray"], groups: ["BritishColumbia"] },
            reminder: { remindPeriod: 270 }
        }, {
            id: "18e258dd-5248-4eb4-99b5-1f740983bf49",
            sequenceId: null,
            type: "Notice",
            source: "Operate",
            sourceNotificationId: "Operate_cijbgd21i0007roh3kez51cnh",
            title: "Guczearpihuwitaevalesenut.",
            notificationTime: "2063-06-02T09:18:51.386Z",
            creationTime: "2016-01-12T13:47:09.079Z",
            severity: "Warn",
            description: "Wisaziunesafajevocsebinboukemihugaczavbiliw.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            attributes: [{ key: "ta", value: { stringValue: "pijkemi" } }],
            lifetime: { expiresIn: 22167 },
            target: { groups: ["NovaScotia"] }
        }, {
            id: "8f57a47c-e179-47de-8e8f-58e92f01942f",
            sequenceId: null,
            type: "OrderStatus",
            source: "OMS",
            sourceNotificationId: "OMS_cijbgh65l0000ish338mr9nvt",
            title: "Jicowcunogtozfeetluhogedlecevifegwartunufofabvizuk.",
            notificationTime: "2088-07-13T00:14:33.380Z",
            creationTime: "2016-01-12T13:50:21.037Z",
            severity: "Info",
            description: "Faslonihivizkeajsozkesuirmokamasisejieserijunvuj.",
            state: "Acknowledged",
            isRead: false,
            revision: 0,
            lifetime: { expiresIn: 45668 },
            target: { users: ["KatharinePerkins", "CeliaGraham"] },
            reminder: { remindPeriod: 90 }
        }]
    }
];
